fix: shiki causes fatal error on hexo 7
Enable shiki will cause a `TypeError: code.split is not a function` error and prevents the blog from generating or serving on hexo 7.3.0 and hexo-renderer-marked 7.0.0. The API has changed and no longer provides an info string, which is embedded into the `code` argument.